In [13]:
import pandas as pd
import plotly.express as px
import seaborn as sns
import plotly as plt

In [20]:
df = pd.read_csv("/Users/dayaneribeiro/Documents/Spiced/da-capstone-project-dayane-ernesto/Cleaned Sets/gen_gap_2019-analysis.csv")
df

,location,sex,age,year,precent_of_prevalence,upper_bound,lower_bound
0,Albania,Male,15-19 years,2010,0.009399,0.015126,0.005307
1,Albania,Female,15-19 years,2010,0.006388,0.010502,0.003393
2,Albania,Both Sexes,15-19 years,2010,0.007886,0.012866,0.004241
3,Albania,Male,20-24 years,2010,0.025625,0.040491,0.015240
4,Albania,Female,20-24 years,2010,0.018424,0.029211,0.010647
...,...,...,...,...,...,...,...
805,Italy,Female,35-39 years,2019,0.015842,0.021173,0.011176
806,Italy,Both Sexes,35-39 years,2019,0.025459,0.032900,0.018591
807,Italy,Male,40-44 years,2019,0.029761,0.040194,0.021383
808,Italy,Female,40-44 years,2019,0.012890,0.018061,0.008861
809,Italy,Both Sexes,40-44 years,2019,0.021248,0.029052,0.015345

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 810 entries, 0 to 809
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   location               810 non-null    object
 1   sex                    810 non-null    object
 2   age                    810 non-null    object
 3   year                   810 non-null    int64
 4   precent_of_prevalence  810 non-null    float64
 5   upper_bound            810 non-null    float64
 6   lower_bound            810 non-null    float64
dtypes: float64(3), int64(1), object(3)
memory usage: 44.4+ KB

In [21]:
df = df.rename(columns = {'precent_of_prevalence': 'prevalence'}, inplace=True)

In [17]:

def define_gen(age):
    if '15-19 years' in age or '20-24 years' in age:
        return 'Gen_Z'
    elif '25-29 years' in age or '30-34 years' in age or '35-39 years' in age:
        return 'Millennial'
    else:
        return 'Gen_X'

In [22]:
fig = px.choropleth(
    df,
    locations="location",
    locationmode="country names",
    color="prevalence",
    hover_name="location",
    animation_frame="age", 
    color_continuous_scale="RdYlBu",
    title="AUD prevalence by Country and Age"
)
fig.update_geos(
    #scope="europe",
    projection_scale=2.5,
    center={"lat": 54, "lon": 15} 
)
#fig.layout.sliders[0].transition.duration = 2000
fig.show()

/var/folders/s4/_zhd9zj1105fnq7y281mkzdc0000gn/T/ipykernel_6296/3903580865.py:1: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig = px.choropleth(

ValueError: String or int arguments are only possible when a DataFrame or an array is provided in the `data_frame` argument. No DataFrame was provided, but argument 'hover_name' is of type str or int.

In [18]:
df['generation'] = df['age'].apply(define_gen)
df.head()

TypeError: 'NoneType' object is not subscriptable

In [ ]:

import matplotlib.pyplot as plt

# 3. (Optional but recommended) filter to avoid duplicates across sex
df_filtered = df[df['sex'] == 'Both Sexes']

# 4. Aggregate mean prevalence by year and generation
grouped = df_filtered.groupby(['year', 'generation'])['precent_of_prevalence'].mean().reset_index()

# 5. Pivot for plotting
pivot_df = grouped.pivot(index='year', columns='generation', values='precent_of_prevalence')

# 6. Plot
plt.figure(figsize=(10,6))
sns.lineplot(
    data=pivot_df
)

plt.xlabel('Year')
plt.ylabel('Prevalence')
plt.title('Prevalence by Generation Over Time')
plt.legend(title="Generation", bbox_to_anchor=(1.05, 1), loc="upper left")

plt.show()

TypeError: 'NoneType' object is not subscriptable

In [ ]:
df1 = pd.read_csv("/Users/dayaneribeiro/Documents/Spiced/da-capstone-project-dayane-ernesto/Cleaned Sets/master_prevalence_2005_2023.csv")
df1

,location,sex,age,year,precent_of_prevalence,upper_bound,lower_bound
0,Albania,Male,15-19 years,2005,0.009183,0.014542,0.005085
1,Albania,Female,15-19 years,2005,0.006313,0.010442,0.003289
2,Albania,Both Sexes,15-19 years,2005,0.007746,0.012591,0.004332
3,Albania,Male,20-24 years,2005,0.025058,0.039093,0.014484
4,Albania,Female,20-24 years,2005,0.018224,0.029243,0.010444
...,...,...,...,...,...,...,...
15043,United Kingdom,Female,35-39 years,2023,0.020648,0.025918,0.015691
15044,United Kingdom,Both Sexes,35-39 years,2023,0.049123,0.060955,0.038354
15045,United Kingdom,Male,40-44 years,2023,0.078855,0.099908,0.060850
15046,United Kingdom,Female,40-44 years,2023,0.019155,0.025240,0.014407
15047,United Kingdom,Both Sexes,40-44 years,2023,0.048010,0.061964,0.037021

In [ ]:
df1['generation'] = df1['age'].apply(define_gen)
df1.head()

,location,sex,age,year,precent_of_prevalence,upper_bound,lower_bound,generation
0,Albania,Male,15-19 years,2005,0.009183,0.014542,0.005085,Gen_Z
1,Albania,Female,15-19 years,2005,0.006313,0.010442,0.003289,Gen_Z
2,Albania,Both Sexes,15-19 years,2005,0.007746,0.012591,0.004332,Gen_Z
3,Albania,Male,20-24 years,2005,0.025058,0.039093,0.014484,Gen_Z
4,Albania,Female,20-24 years,2005,0.018224,0.029243,0.010444,Gen_Z

In [ ]:
pivot_df.plot()
data=pivot_df[pivot_df["location"] == "Germany", "Ireland"]
plt.xlabel('Year')
plt.ylabel('Prevalence')
plt.title('Prevalence by Generation Over Time')
plt.legend(title="Generation", bbox_to_anchor=(1.05, 1), loc="upper left")
#plt.tight_layout()
plt.show()

NameError: name 'pivot_df' is not defined