In [2]:
pip install kagglehub

Requirement already satisfied: kagglehub in /opt/miniconda3/lib/python3.13/site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /opt/miniconda3/lib/python3.13/site-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in /opt/miniconda3/lib/python3.13/site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in /opt/miniconda3/lib/python3.13/site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /opt/miniconda3/lib/python3.13/site-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /opt/miniconda3/lib/python3.13/site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in /opt/miniconda3/lib/python3.13/site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (7.34.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/lib/python3.13/site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/miniconda3/lib/python3.13/site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/miniconda3/lib/python3.13/site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/miniconda3/lib/python3.13/site-packages (from requests->kagglehub) (2025.8.3)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ibrahimqasimi/global-alcohol-consumption-who-20002022")

print("Path to dataset files:", path)

/opt/miniconda3/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /Users/dayaneribeiro/.cache/kagglehub/datasets/ibrahimqasimi/global-alcohol-consumption-who-20002022/versions/1

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("./who_alcohol_total_per_capita_2000_2022_clean.csv")

df.head()

,country,iso3,year,sex,alcohol_liters_per_capita,lower_ci,upper_ci,ci_width,IndicatorCode
0,Italy,ITA,2003,Both sexes,9.622988,7.965011,11.388622,3.423611,SA_0000001688
1,"Tanzania, United Republic of",TZA,2006,Both sexes,6.337646,4.767623,8.109324,3.341701,SA_0000001688
2,Cyprus,CYP,2017,Both sexes,6.117152,4.627244,7.798063,3.170819,SA_0000001688
3,Sierra Leone,SLE,2019,Both sexes,0.253228,0.100851,0.567434,0.466583,SA_0000001688
4,Philippines,PHL,2017,Both sexes,6.023875,4.681733,7.536645,2.854912,SA_0000001688

In [6]:
df.describe

<bound method NDFrame.describe of                            country iso3  year         sex  \
0                            Italy  ITA  2003  Both sexes
1     Tanzania, United Republic of  TZA  2006  Both sexes
2                           Cyprus  CYP  2017  Both sexes
3                     Sierra Leone  SLE  2019  Both sexes
4                      Philippines  PHL  2017  Both sexes
...                            ...  ...   ...         ...
4319                    Azerbaijan  AZE  2019  Both sexes
4320                       Denmark  DNK  2003  Both sexes
4321                         Japan  JPN  2021  Both sexes
4322                         Italy  ITA  2015  Both sexes
4323                        Greece  GRC  2009  Both sexes

      alcohol_liters_per_capita   lower_ci   upper_ci  ci_width  IndicatorCode
0                      9.622988   7.965011  11.388622  3.423611  SA_0000001688
1                      6.337646   4.767623   8.109324  3.341701  SA_0000001688
2                      6.117152   4.627244   7.798063  3.170819  SA_0000001688
3                      0.253228   0.100851   0.567434  0.466583  SA_0000001688
4                      6.023875   4.681733   7.536645  2.854912  SA_0000001688
...                         ...        ...        ...       ...            ...
4319                   2.296669   1.388574   3.261534  1.872960  SA_0000001688
4320                  12.090151  10.413569  13.977235  3.563666  SA_0000001688
4321                   6.310086   5.040318   7.638079  2.597762  SA_0000001688
4322                   7.738343   6.424931   9.213857  2.788927  SA_0000001688
4323                   9.058701   7.354858  10.664988  3.310130  SA_0000001688

[4324 rows x 9 columns]>

In [9]:
with open("../Ernestos_finds/2019_Gesundheit_in_Deutschlandaktuell_Variablen.csv") as f:
    for i in range(10):
        print(f.readline())

Variablenübersicht (nur generierte und nicht interne Variablen);;;;;;;;;;;;;;

;;;;;;;;;;;;;;

;;;;;;;;;;;;;;

Studie;Thema und Fragebogenausschnitt;Unterthema;Varname;;DStyp ID;Datensatztyp;Varlabel;Originalvariable;Dateninfo;SyntaxGenVar;VarLevel; Valuelabel Set;Ausprägungen;Text Dt

GEDA19;Krankheiten (1101);Koronare Herzkrankheit (110102);KHbbmyo12;;17;Abt2_DS;Herzinfarkt/chron. Beschw.: I.d.l. 12 Mon.;KHmyo12 BBmyo12;"EHIS Wave 3_Indicators_manual_(2019-06-24).pdf: 3.1.2. Diseases and chronic conditions, S.6/7

Analog GEDA14 in CATI getrennte Fragestellung zum Herzinfarkt (KHmyo12/CD1C1) und chronische Beschwerden nach Herzinfarkt (BBmyo12/CD1C2) i.d.l. 12 Monaten zusammengefasst in einer Variable (KHbbmyo12/CD1C) laut EHIS-Vorgabe.

Wenn eine der Fragen (KHmyo12, BBmyo12) mit ""Ja"" beantwortet wurde, wird KHbbmyo12 auf ""Ja"" gesetzt. Wenn beide Fragen mit ""Nein"" beantwortet wurden, wird KHbbmyo12 auf ""Nein"" gesetzt.

Missing: wenn eine Frage mit Keine Angabe oder Weiß Nicht und die andere Frage ebenso oder mit Nein beantwortet wurde";"*Zur Info: KHbbmyo12 entspricht EHIS Varname CD1C;

IF KHmyo12 < 1 or BBmyo12 < 1 THEN KHbbmyo12=.;

IF KHmyo12=1 or BBmyo12=1 THEN KHbbmyo12=1; /*Ja*/

In [13]:
df1 = pd.read_csv(
    "../Ernestos_finds/2019_Gesundheit_in_Deutschlandaktuell_Variablen.csv",
    sep=";"
)
df1

,Variablenübersicht (nur generierte und nicht interne Variablen),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Studie,Thema und Fragebogenausschnitt,Unterthema,Varname,NaN,DStyp ID,Datensatztyp,Varlabel,Originalvariable,Dateninfo,SyntaxGenVar,VarLevel,Valuelabel Set,Ausprägungen,Text Dt
3,GEDA19,Krankheiten (1101),Koronare Herzkrankheit (110102),KHbbmyo12,NaN,17,Abt2_DS,Herzinfarkt/chron. Beschw.: I.d.l. 12 Mon.,KHmyo12 BBmyo12,EHIS Wave 3_Indicators_manual_(2019-06-24).pdf...,*Zur Info: KHbbmyo12 entspricht EHIS Varname C...,Nominal,JaNeinWnKA,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-99,Keine Angabe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77,2020_KW38
1747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78,2020_KW39
1748,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79,2020_KW40
1749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,2019_KW21
1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,2019_KW22

In [14]:
df2 = pd.read_csv(
    "../Ernestos_finds/estat_hlth_ehis_al1c.tsv",
    sep="\t"
)
df2

      freq,unit,frequenc,sex,age,citizen,geo\TIME_PERIOD 2014  2019
0                      A,PC,DAY,F,TOTAL,EU27_2020_FOR,AT    :   2.0
1                      A,PC,DAY,F,TOTAL,EU27_2020_FOR,BE    :   4.5
2                      A,PC,DAY,F,TOTAL,EU27_2020_FOR,BG    :     0
3                      A,PC,DAY,F,TOTAL,EU27_2020_FOR,CY    :   0.3
4                      A,PC,DAY,F,TOTAL,EU27_2020_FOR,CZ    :     0
...                                                  ...   ...   ...
69337                    A,PC,WEEK,T,Y_GE75,NEU28_FOR,SE   : u    :
69338                    A,PC,WEEK,T,Y_GE75,NEU28_FOR,SI   : u    :
69339                    A,PC,WEEK,T,Y_GE75,NEU28_FOR,SK   : u    :
69340                    A,PC,WEEK,T,Y_GE75,NEU28_FOR,TR   : u    :
69341                    A,PC,WEEK,T,Y_GE75,NEU28_FOR,UK   : u    :

[69342 rows x 3 columns]

In [15]:
df3 = pd.read_csv(
    "../Ernestos_finds/estat_hlth_ehis_al1c.tsv.gz",
    sep="\t"
)
df3

      freq,unit,frequenc,sex,age,citizen,geo\TIME_PERIOD 2014  2019
0                      A,PC,DAY,F,TOTAL,EU27_2020_FOR,AT    :   2.0
1                      A,PC,DAY,F,TOTAL,EU27_2020_FOR,BE    :   4.5
2                      A,PC,DAY,F,TOTAL,EU27_2020_FOR,BG    :     0
3                      A,PC,DAY,F,TOTAL,EU27_2020_FOR,CY    :   0.3
4                      A,PC,DAY,F,TOTAL,EU27_2020_FOR,CZ    :     0
...                                                  ...   ...   ...
69337                    A,PC,WEEK,T,Y_GE75,NEU28_FOR,SE   : u    :
69338                    A,PC,WEEK,T,Y_GE75,NEU28_FOR,SI   : u    :
69339                    A,PC,WEEK,T,Y_GE75,NEU28_FOR,SK   : u    :
69340                    A,PC,WEEK,T,Y_GE75,NEU28_FOR,TR   : u    :
69341                    A,PC,WEEK,T,Y_GE75,NEU28_FOR,UK   : u    :

[69342 rows x 3 columns]

In [18]:
df4 = pd.read_csv("./consumption_levels/data/SA_0000001400.csv")
df4

,Id,IndicatorCode,SpatialDimension,SpatialDimensionValueCode,ParentLocationCode,ParentLocation,TimeDimension,TimeDim,DisaggregatingDimension1,DisaggregatingDimension1ValueCode,...,DataSourceDimensionValueCode,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,933255,SA_0000001400,COUNTRY,FIN,EUR,Europe,YEAR,1998,ALCOHOLTYPE,ALCOHOLTYPE_SA_BEER,...,DATASOURCE_GISAHFIN,4.38,4.380000,NaN,NaN,NaN,2018-05-11T09:15:46Z,1998,1998-01-01,1998-12-31
1,933909,SA_0000001400,COUNTRY,PER,AMR,Americas,YEAR,2020,ALCOHOLTYPE,ALCOHOLTYPE_SA_BEER,...,DATASOURCE_GISAHPER,2.50,2.524785,NaN,NaN,NaN,2025-06-27T08:55:48Z,2020,2020-01-01,2020-12-31
2,934148,SA_0000001400,COUNTRY,ARM,EUR,Europe,YEAR,1995,ALCOHOLTYPE,ALCOHOLTYPE_SA_SPIRITS,...,DATASOURCE_GISAHARM,2.43,2.430000,NaN,NaN,NaN,2018-05-11T09:12:40Z,1995,1995-01-01,1995-12-31
3,934196,SA_0000001400,COUNTRY,ESP,EUR,Europe,YEAR,1986,ALCOHOLTYPE,ALCOHOLTYPE_SA_BEER,...,DATASOURCE_GISAHESP,3.99,3.990000,NaN,NaN,NaN,2018-05-11T09:09:07Z,1986,1986-01-01,1986-12-31
4,934198,SA_0000001400,COUNTRY,LBR,AFR,Africa,YEAR,1991,ALCOHOLTYPE,ALCOHOLTYPE_SA_BEER,...,DATASOURCE_GISAHLBR,0.18,0.180000,NaN,NaN,NaN,2018-05-11T09:17:44Z,1991,1991-01-01,1991-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50433,10007014,SA_0000001400,COUNTRY,THA,SEAR,South-East Asia,YEAR,1994,ALCOHOLTYPE,ALCOHOLTYPE_SA_TOTAL,...,DATASOURCE_GISAHTHA,5.07,5.070000,NaN,NaN,NaN,2018-05-11T09:18:01Z,1994,1994-01-01,1994-12-31
50434,10007157,SA_0000001400,COUNTRY,BWA,AFR,Africa,YEAR,1964,ALCOHOLTYPE,ALCOHOLTYPE_SA_TOTAL,...,DATASOURCE_GISAHBWA,5.83,5.830000,NaN,NaN,NaN,2018-05-11T09:18:58Z,1964,1964-01-01,1964-12-31
50435,10007553,SA_0000001400,COUNTRY,SVK,EUR,Europe,YEAR,2017,ALCOHOLTYPE,ALCOHOLTYPE_SA_BEER,...,DATASOURCE_GISAHSVK,3.40,3.430000,NaN,NaN,NaN,2025-06-27T08:55:48Z,2017,2017-01-01,2017-12-31
50436,10007738,SA_0000001400,COUNTRY,BOL,AMR,Americas,YEAR,1976,ALCOHOLTYPE,ALCOHOLTYPE_SA_SPIRITS,...,DATASOURCE_GISAHBOL,2.14,2.140000,NaN,NaN,NaN,2018-05-11T09:03:30Z,1976,1976-01-01,1976-12-31
50437,10007927,SA_0000001400,COUNTRY,SUR,AMR,Americas,YEAR,1998,ALCOHOLTYPE,ALCOHOLTYPE_SA_SPIRITS,...,DATASOURCE_GISAHSUR,3.71,3.710000,NaN,NaN,NaN,2018-05-11T09:02:20Z,1998,1998-01-01,1998-12-31

In [19]:
df5 = pd.read_csv("./consumption_levels/data/SA_0000001404.csv")
df5

,Id,IndicatorCode,SpatialDimension,SpatialDimensionValueCode,ParentLocationCode,ParentLocation,TimeDimension,TimeDim,DisaggregatingDimension1,DisaggregatingDimension1ValueCode,...,DataSourceDimensionValueCode,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,933733,SA_0000001404,COUNTRY,TGO,AFR,Africa,YEAR,2004,SEX,SEX_BTSX,...,NaN,4.2 [1.2 - 7.7],4.214251,1.160305,7.746598,NaN,2024-06-21T09:03:11Z,2004,2004-01-01,2004-12-31
1,1431,SA_0000001404,COUNTRY,NZL,WPR,Western Pacific,YEAR,2010,SEX,SEX_FMLE,...,NaN,6.6 [4.6 - 8.7],6.586208,4.631288,8.679614,NaN,2024-06-21T09:03:11Z,2010,2010-01-01,2010-12-31
2,4020,SA_0000001404,COUNTRY,DEU,EUR,Europe,YEAR,2020,SEX,SEX_FMLE,...,NaN,7.4 [5.2 - 9.5],7.365819,5.230310,9.518477,Data is for 2020 only; it is not a three-year ...,2024-06-21T09:03:11Z,2020,2020-01-01,2020-12-31
3,5214,SA_0000001404,COUNTRY,ARG,AMR,Americas,YEAR,2016,SEX,SEX_BTSX,...,NaN,12.0 [8.4 - 15.8],12.030890,8.407949,15.768039,NaN,2024-06-21T09:03:11Z,2016,2016-01-01,2016-12-31
4,8174,SA_0000001404,COUNTRY,SLB,WPR,Western Pacific,YEAR,2020,SEX,SEX_MLE,...,NaN,6.8 [1.6 - 12.8],6.840528,1.560743,12.794928,Data is for 2020 only; it is not a three-year ...,2024-06-21T09:03:11Z,2020,2020-01-01,2020-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11788,10006300,SA_0000001404,COUNTRY,AUT,EUR,Europe,YEAR,2005,SEX,SEX_FMLE,...,NaN,7.9 [5.9 - 10.3],7.934389,5.871716,10.262032,NaN,2024-06-21T09:03:11Z,2005,2005-01-01,2005-12-31
11789,10006612,SA_0000001404,COUNTRY,LVA,EUR,Europe,YEAR,2004,SEX,SEX_BTSX,...,NaN,14.2 [9.2 - 19.3],14.216890,9.249689,19.256902,NaN,2024-06-21T09:03:11Z,2004,2004-01-01,2004-12-31
11790,10006664,SA_0000001404,COUNTRY,LVA,EUR,Europe,YEAR,2019,SEX,SEX_BTSX,...,NaN,17.4 [12.5 - 22.4],17.393706,12.483185,22.381548,NaN,2024-06-21T09:03:11Z,2019,2019-01-01,2019-12-31
11791,10007081,SA_0000001404,COUNTRY,FJI,WPR,Western Pacific,YEAR,2019,SEX,SEX_MLE,...,NaN,14.5 [6.4 - 23.2],14.509541,6.412728,23.156451,NaN,2024-06-21T09:03:11Z,2019,2019-01-01,2019-12-31
11792,10007800,SA_0000001404,COUNTRY,VEN,AMR,Americas,YEAR,2014,SEX,SEX_FMLE,...,NaN,7.6 [5.0 - 10.6],7.622607,4.980277,10.626688,NaN,2024-06-21T09:03:11Z,2014,2014-01-01,2014-12-31

In [20]:
df6 = pd.read_csv("./consumption_levels/data/SA_0000001688.csv")
df6

,Id,IndicatorCode,SpatialDimension,SpatialDimensionValueCode,ParentLocationCode,ParentLocation,TimeDimension,TimeDim,DisaggregatingDimension1,DisaggregatingDimension1ValueCode,...,DataSourceDimensionValueCode,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,8060337,SA_0000001688,COUNTRY,UZB,EUR,Europe,YEAR,2017,SEX,SEX_BTSX,...,NaN,2.8 [1.9 - 3.6],2.755196,1.942710,3.611217,NaN,2025-05-13T09:35:54Z,2017,2017-01-01,2017-12-31
1,9768406,SA_0000001688,COUNTRY,GNB,AFR,Africa,YEAR,2007,SEX,SEX_BTSX,...,NaN,2.9 [1.9 - 3.9],2.905023,1.880523,3.910574,NaN,2025-05-13T09:35:54Z,2007,2007-01-01,2007-12-31
2,6536843,SA_0000001688,COUNTRY,SYR,EMR,Eastern Mediterranean,YEAR,2000,SEX,SEX_BTSX,...,NaN,1.3 [0.8 - 2.1],1.346784,0.757818,2.056904,NaN,2025-05-13T09:35:54Z,2000,2000-01-01,2000-12-31
3,6536847,SA_0000001688,COUNTRY,IDN,SEAR,South-East Asia,YEAR,2002,SEX,SEX_BTSX,...,NaN,0.1 [0.0 - 0.3],0.075991,0.021509,0.261398,NaN,2025-05-13T09:35:54Z,2002,2002-01-01,2002-12-31
4,8245021,SA_0000001688,COUNTRY,IRN,EMR,Eastern Mediterranean,YEAR,2012,SEX,SEX_BTSX,...,NaN,0.2 [0.0 - 0.6],0.222215,0.012935,0.616851,NaN,2025-05-13T09:35:54Z,2012,2012-01-01,2012-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5400,9999930,SA_0000001688,COUNTRY,ITA,EUR,Europe,YEAR,2015,SEX,SEX_BTSX,...,NaN,7.7 [6.4 - 9.2],7.738343,6.424931,9.213857,NaN,2025-05-13T09:35:54Z,2015,2015-01-01,2015-12-31
5401,9999962,SA_0000001688,UNREGION,53,NaN,NaN,YEAR,2011,SEX,SEX_BTSX,...,NaN,10.6 [9.3 - 12.2],10.636844,9.280464,12.236140,NaN,2025-05-13T09:35:54Z,2011,2011-01-01,2011-12-31
5402,10005131,SA_0000001688,COUNTRY,HTI,AMR,Americas,YEAR,2007,SEX,SEX_BTSX,...,NaN,4.2 [3.1 - 5.3],4.162244,3.112734,5.330119,NaN,2025-05-13T09:35:54Z,2007,2007-01-01,2007-12-31
5403,10005348,SA_0000001688,UNREGION,13,NaN,NaN,YEAR,2014,SEX,SEX_BTSX,...,NaN,4.7 [3.8 - 5.7],4.667350,3.775360,5.664963,NaN,2025-05-13T09:35:54Z,2014,2014-01-01,2014-12-31
5404,10006538,SA_0000001688,COUNTRY,GRC,EUR,Europe,YEAR,2009,SEX,SEX_BTSX,...,NaN,9.1 [7.4 - 10.7],9.058701,7.354858,10.664988,NaN,2025-05-13T09:35:54Z,2009,2009-01-01,2009-12-31

In [22]:
df7 = pd.read_csv("./consumption_levels/data/SA_0000001747.csv")
df7

,Id,IndicatorCode,SpatialDimension,SpatialDimensionValueCode,ParentLocationCode,ParentLocation,TimeDimension,TimeDim,DisaggregatingDimension1,DisaggregatingDimension1ValueCode,...,DataSourceDimensionValueCode,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,1946596,SA_0000001747,COUNTRY,JOR,EMR,Eastern Mediterranean,YEAR,2011,NaN,NaN,...,NaN,0.4 [0.1 - 0.8],0.445462,0.146069,0.760611,NaN,2025-06-18T14:11:35Z,2011,2011-01-01,2011-12-31
1,336083,SA_0000001747,COUNTRY,TUN,EMR,Eastern Mediterranean,YEAR,2002,NaN,NaN,...,NaN,1.3 [0.8 - 1.9],1.317798,0.807944,1.901487,NaN,2025-06-18T14:11:35Z,2002,2002-01-01,2002-12-31
2,374263,SA_0000001747,COUNTRY,AZE,EUR,Europe,YEAR,2008,NaN,NaN,...,NaN,0.6 [0.3 - 1.0],0.568046,0.251125,0.964423,NaN,2025-06-18T14:11:35Z,2008,2008-01-01,2008-12-31
3,8251392,SA_0000001747,COUNTRY,PRT,EUR,Europe,YEAR,2012,NaN,NaN,...,NaN,10.0 [8.4 - 11.7],10.040000,8.401023,11.692693,NaN,2025-06-18T14:11:35Z,2012,2012-01-01,2012-12-31
4,558647,SA_0000001747,COUNTRY,CRI,AMR,Americas,YEAR,2013,NaN,NaN,...,NaN,3.1 [2.2 - 4.0],3.103333,2.248117,3.992306,NaN,2025-06-18T14:11:35Z,2013,2013-01-01,2013-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4296,9979557,SA_0000001747,COUNTRY,AZE,EUR,Europe,YEAR,2017,NaN,NaN,...,NaN,0.6 [0.2 - 1.0],0.573333,0.220763,0.954461,NaN,2025-06-18T14:11:35Z,2017,2017-01-01,2017-12-31
4297,9981203,SA_0000001747,COUNTRY,PAN,AMR,Americas,YEAR,2022,NaN,NaN,...,NaN,5.8 [4.5 - 7.0],5.785026,4.524391,6.990541,NaN,2025-06-18T14:11:35Z,2022,2022-01-01,2022-12-31
4298,9987174,SA_0000001747,COUNTRY,KOR,WPR,Western Pacific,YEAR,2006,NaN,NaN,...,NaN,9.0 [7.5 - 10.6],8.970000,7.526591,10.579815,NaN,2025-06-18T14:11:35Z,2006,2006-01-01,2006-12-31
4299,10003932,SA_0000001747,COUNTRY,KEN,AFR,Africa,YEAR,2021,NaN,NaN,...,NaN,2.0 [1.3 - 2.7],1.974307,1.281693,2.684523,NaN,2025-06-18T14:11:35Z,2021,2021-01-01,2021-12-31
4300,10006157,SA_0000001747,COUNTRY,ERI,AFR,Africa,YEAR,2002,NaN,NaN,...,NaN,0.6 [0.2 - 1.0],0.627650,0.238899,1.030884,NaN,2025-06-18T14:11:35Z,2002,2002-01-01,2002-12-31

In [23]:
df8 = pd.read_csv("./consumption_levels/data/SA_0000001751.csv")
df8

,Id,IndicatorCode,SpatialDimension,SpatialDimensionValueCode,ParentLocationCode,ParentLocation,TimeDimension,TimeDim,DisaggregatingDimension1,DisaggregatingDimension1ValueCode,...,DataSourceDimensionValueCode,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,936195,SA_0000001751,COUNTRY,MWI,AFR,Africa,YEAR,2016,SEX,SEX_BTSX,...,NaN,24.9 [10.0 - 40.8],24.859506,10.038124,40.814935,NaN,2024-06-21T09:04:27Z,2016,2016-01-01,2016-12-31
1,936385,SA_0000001751,COUNTRY,LAO,WPR,Western Pacific,YEAR,2016,SEX,SEX_MLE,...,NaN,58.4 [39.7 - 77.7],58.426421,39.658573,77.654501,NaN,2024-06-21T09:04:27Z,2016,2016-01-01,2016-12-31
2,936577,SA_0000001751,COUNTRY,RWA,AFR,Africa,YEAR,2013,SEX,SEX_FMLE,...,NaN,4.9 [1.0 - 9.6],4.880139,0.998824,9.579881,NaN,2024-06-21T09:04:27Z,2013,2013-01-01,2013-12-31
3,926,SA_0000001751,COUNTRY,IRL,EUR,Europe,YEAR,2006,SEX,SEX_BTSX,...,NaN,37.0 [28.5 - 46.4],37.024092,28.486083,46.353342,NaN,2024-06-21T09:04:27Z,2006,2006-01-01,2006-12-31
4,1245,SA_0000001751,COUNTRY,GTM,AMR,Americas,YEAR,2019,SEX,SEX_BTSX,...,NaN,10.2 [3.3 - 17.5],10.239397,3.272656,17.530893,NaN,2024-06-21T09:04:27Z,2019,2019-01-01,2019-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11782,10003948,SA_0000001751,COUNTRY,BRB,AMR,Americas,YEAR,2013,SEX,SEX_BTSX,...,NaN,34.1 [21.9 - 46.9],34.053135,21.852898,46.902717,NaN,2024-06-21T09:04:27Z,2013,2013-01-01,2013-12-31
11783,10004274,SA_0000001751,COUNTRY,LKA,SEAR,South-East Asia,YEAR,2016,SEX,SEX_FMLE,...,NaN,8.4 [4.0 - 13.4],8.353783,4.011558,13.379855,NaN,2024-06-21T09:04:27Z,2016,2016-01-01,2016-12-31
11784,10006199,SA_0000001751,COUNTRY,AUT,EUR,Europe,YEAR,2000,SEX,SEX_BTSX,...,NaN,35.4 [26.7 - 44.6],35.393007,26.730971,44.619258,NaN,2024-06-21T09:04:27Z,2000,2000-01-01,2000-12-31
11785,10006507,SA_0000001751,COUNTRY,ERI,AFR,Africa,YEAR,2017,SEX,SEX_MLE,...,NaN,21.9 [5.0 - 42.8],21.866190,4.956739,42.782326,NaN,2024-06-21T09:04:27Z,2017,2017-01-01,2017-12-31
11786,10006887,SA_0000001751,COUNTRY,TCD,AFR,Africa,YEAR,2020,SEX,SEX_MLE,...,NaN,37.0 [6.8 - 68.7],36.979334,6.757891,68.720219,Data is for 2020 only; it is not a three-year ...,2024-06-21T09:04:27Z,2020,2020-01-01,2020-12-31

In [24]:
df9 = pd.read_csv("./consumption_levels/data/SA_0000001818.csv")
df9

,Id,IndicatorCode,SpatialDimension,SpatialDimensionValueCode,ParentLocationCode,ParentLocation,TimeDimension,TimeDim,DisaggregatingDimension1,DisaggregatingDimension1ValueCode,...,DataSourceDimensionValueCode,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,1984773,SA_0000001818,COUNTRY,BWA,AFR,Africa,YEAR,2027,SEX,SEX_BTSX,...,NaN,8.3 [4.8 - 11.8],8.319317,4.816017,11.822617,NaN,2024-06-21T09:06:15Z,2027,2027-01-01,2027-12-31
1,2016560,SA_0000001818,COUNTRY,MWI,AFR,Africa,YEAR,2021,SEX,SEX_BTSX,...,NaN,3.6 [1.5 - 5.6],3.567498,1.521598,5.613398,NaN,2024-06-21T09:06:15Z,2021,2021-01-01,2021-12-31
2,8225991,SA_0000001818,COUNTRY,ROU,EUR,Europe,YEAR,2025,NaN,NaN,...,NaN,13.8 [7.5-20.1],13.800000,7.500000,20.100000,NaN,2018-08-24T12:05:11Z,2025,2025-01-01,2025-12-31
3,2226452,SA_0000001818,COUNTRY,COD,AFR,Africa,YEAR,2024,SEX,SEX_BTSX,...,NaN,2.0 [0.4 - 3.6],2.010504,0.422551,3.598457,NaN,2024-06-21T09:06:15Z,2024,2024-01-01,2024-12-31
4,5204095,SA_0000001818,COUNTRY,CIV,AFR,Africa,YEAR,2027,SEX,SEX_BTSX,...,NaN,2.8 [0.3 - 5.3],2.789737,0.261163,5.318311,NaN,2024-06-21T09:06:15Z,2027,2027-01-01,2027-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2109,9762002,SA_0000001818,COUNTRY,GEO,EUR,Europe,YEAR,2023,SEX,SEX_BTSX,...,NaN,14.8 [10.2 - 19.3],14.760406,10.194089,19.326724,NaN,2024-06-21T09:06:15Z,2023,2023-01-01,2023-12-31
2110,9932089,SA_0000001818,COUNTRY,HND,AMR,Americas,YEAR,2022,SEX,SEX_BTSX,...,NaN,3.1 [1.6 - 4.7],3.142644,1.579192,4.706096,NaN,2024-06-21T09:06:15Z,2022,2022-01-01,2022-12-31
2111,9957166,SA_0000001818,COUNTRY,ZMB,AFR,Africa,YEAR,2025,SEX,SEX_BTSX,...,NaN,3.8 [2.0 - 5.6],3.785107,2.008349,5.561865,NaN,2024-06-21T09:06:15Z,2025,2025-01-01,2025-12-31
2112,9975335,SA_0000001818,COUNTRY,TLS,SEAR,South-East Asia,YEAR,2025,NaN,NaN,...,NaN,5.5 [3.3-7.6],5.500000,3.300000,7.600000,NaN,2018-08-24T12:05:13Z,2025,2025-01-01,2025-12-31
2113,9987994,SA_0000001818,COUNTRY,LKA,SEAR,South-East Asia,YEAR,2021,SEX,SEX_BTSX,...,NaN,2.9 [1.3 - 4.5],2.892633,1.329343,4.455923,NaN,2024-06-21T09:06:15Z,2021,2021-01-01,2021-12-31

In [25]:
df10 = pd.read_csv("./consumption_levels/data/SA_0000001821.csv")
df10

,Id,IndicatorCode,SpatialDimension,SpatialDimensionValueCode,ParentLocationCode,ParentLocation,TimeDimension,TimeDim,DisaggregatingDimension1,DisaggregatingDimension1ValueCode,...,DataSourceDimensionValueCode,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,6399402,SA_0000001821,COUNTRY,POL,EUR,Europe,YEAR,2021,NaN,NaN,...,NaN,1.3 [0.5 - 2.2],1.323619,0.491495,2.232430,NaN,2025-06-18T14:11:35Z,2021,2021-01-01,2021-12-31
1,412460,SA_0000001821,COUNTRY,MKD,EUR,Europe,YEAR,2018,NaN,NaN,...,NaN,0.9 [0.3 - 1.8],0.931135,0.264232,1.779693,NaN,2025-06-18T14:11:35Z,2018,2018-01-01,2018-12-31
2,3694549,SA_0000001821,COUNTRY,BRB,AMR,Americas,YEAR,2020,NaN,NaN,...,NaN,0.7 [0.2 - 1.4],0.691017,0.169792,1.371724,NaN,2025-06-18T14:11:35Z,2020,2020-01-01,2020-12-31
3,6809918,SA_0000001821,COUNTRY,TJK,EUR,Europe,YEAR,2013,NaN,NaN,...,NaN,0.0 [0.0 - 0.1],0.005168,0.000000,0.069533,NaN,2025-06-18T14:11:35Z,2013,2013-01-01,2013-12-31
4,3987072,SA_0000001821,COUNTRY,CHL,AMR,Americas,YEAR,2002,NaN,NaN,...,NaN,0.5 [0.1 - 1.1],0.517086,0.090076,1.093133,NaN,2025-06-18T14:11:35Z,2002,2002-01-01,2002-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4296,9991290,SA_0000001821,COUNTRY,HUN,EUR,Europe,YEAR,2021,NaN,NaN,...,NaN,0.8 [0.2 - 1.6],0.829595,0.232225,1.596694,NaN,2025-06-18T14:11:35Z,2021,2021-01-01,2021-12-31
4297,9991450,SA_0000001821,COUNTRY,BTN,SEAR,South-East Asia,YEAR,2011,NaN,NaN,...,NaN,2.6 [1.4 - 3.9],2.591057,1.418440,3.949857,NaN,2025-06-18T14:11:35Z,2011,2011-01-01,2011-12-31
4298,9997223,SA_0000001821,COUNTRY,GUY,AMR,Americas,YEAR,2005,NaN,NaN,...,NaN,0.2 [0.0 - 0.6],0.205914,0.011866,0.563579,NaN,2025-06-18T14:11:35Z,2005,2005-01-01,2005-12-31
4299,9999022,SA_0000001821,COUNTRY,BLR,EUR,Europe,YEAR,2004,NaN,NaN,...,NaN,0.7 [0.1 - 1.3],0.664325,0.131114,1.303317,NaN,2025-06-18T14:11:35Z,2004,2004-01-01,2004-12-31
4300,10003387,SA_0000001821,COUNTRY,ITA,EUR,Europe,YEAR,2020,NaN,NaN,...,NaN,0.5 [0.1 - 1.0],0.497406,0.093926,1.028742,NaN,2025-06-18T14:11:35Z,2020,2020-01-01,2020-12-31

In [26]:
df11 = pd.read_csv("./consumption_levels/data/SA_0000001823.csv")
df11

,Id,IndicatorCode,SpatialDimension,SpatialDimensionValueCode,ParentLocationCode,ParentLocation,TimeDimension,TimeDim,DisaggregatingDimension1,DisaggregatingDimension1ValueCode,...,DataSourceDimensionValueCode,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,952,SA_0000001823,COUNTRY,JOR,EMR,Eastern Mediterranean,YEAR,2016,NaN,NaN,...,NaN,0.0 [0.0 - 0.0],0.000000,0.000000,0.000000,NaN,2025-06-18T14:11:35Z,2016,2016-01-01,2016-12-31
1,2519,SA_0000001823,COUNTRY,ERI,AFR,Africa,YEAR,2011,NaN,NaN,...,NaN,0.0 [0.0 - 0.0],0.002985,-0.043591,0.048535,NaN,2025-06-18T14:11:35Z,2011,2011-01-01,2011-12-31
2,3307,SA_0000001823,COUNTRY,SLE,AFR,Africa,YEAR,2012,NaN,NaN,...,NaN,0.0 [0.0 - 0.0],0.000000,0.000000,0.000000,NaN,2025-06-18T14:11:35Z,2012,2012-01-01,2012-12-31
3,4214,SA_0000001823,COUNTRY,JPN,WPR,Western Pacific,YEAR,2022,NaN,NaN,...,NaN,0.0 [-0.1 - 0.1],0.004687,-0.051303,0.058384,NaN,2025-06-18T14:11:35Z,2022,2022-01-01,2022-12-31
4,9189,SA_0000001823,COUNTRY,PRK,SEAR,South-East Asia,YEAR,2015,NaN,NaN,...,NaN,0.0 [0.0 - 0.0],0.000000,0.000000,0.000000,NaN,2025-06-18T14:11:35Z,2015,2015-01-01,2015-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4319,9990762,SA_0000001823,COUNTRY,CIV,AFR,Africa,YEAR,2022,NaN,NaN,...,NaN,0.0 [0.0 - 0.0],0.000943,-0.024466,0.025744,NaN,2025-06-18T14:11:35Z,2022,2022-01-01,2022-12-31
4320,9993053,SA_0000001823,COUNTRY,MRT,AFR,Africa,YEAR,2017,NaN,NaN,...,NaN,0.0 [0.0 - 0.0],0.000000,0.000000,0.000000,NaN,2025-06-18T14:11:35Z,2017,2017-01-01,2017-12-31
4321,9999258,SA_0000001823,COUNTRY,COL,AMR,Americas,YEAR,2007,NaN,NaN,...,NaN,0.0 [-0.1 - 0.2],0.039892,-0.119659,0.204412,NaN,2025-06-18T14:11:35Z,2007,2007-01-01,2007-12-31
4322,10007529,SA_0000001823,COUNTRY,AUS,WPR,Western Pacific,YEAR,2017,NaN,NaN,...,NaN,-0.2 [-0.4 - 0.2],-0.152810,-0.448201,0.154539,NaN,2025-06-18T14:11:35Z,2017,2017-01-01,2017-12-31
4323,10007592,SA_0000001823,COUNTRY,RUS,EUR,Europe,YEAR,2010,NaN,NaN,...,NaN,0.1 [-0.1 - 0.4],0.118957,-0.135161,0.408069,NaN,2025-06-18T14:11:35Z,2010,2010-01-01,2010-12-31